BillPayingWebsite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BillPayingWebsite.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

BillPayingWebsite/Controllers/HouseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using BillPayerCore.Data;
using BillPayerCore.DataModels;
using BillPayingWebsite.Models;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace BillPayingWebsite.Controllers
{
    // siteurl/house/{action}
    public class HouseController : Controller
    {
        DataContext dbContext = new DataContext();

        private ApplicationUserManager _userManager;

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        [Authorize]
        public async Task<ActionResult> Index()
        {
            
               // var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
                var houses = dbContext.HouseHolds.ToList();
                return View(houses);
            

          
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var household = dbContext.HouseHolds.FirstOrDefault(x => x.Id == id);

            if (household == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }



            var model = new HouseHoldUserModel()
            {
                HouseHold = household
            };

            model.roommatesOwed = new List<RoommatesTotalOwed>();
            decimal totalOwed = 0;
            foreach(User roommate in household.Users)
            {
                RoommatesTotalOwed userOwe = new RoommatesTotalOwed();
                totalOwed = 0;
                foreach (BillSplit bill in roommate.BillSplits)
                {
                    if(household.Bills.Contains(bill.Bill))
                        totalOwed += bill.PortionCost;
                }

                userOwe.User = roommate;
                userOwe.totalDue = totalOwed;
                model.roommatesOwed.Add(userOwe);


            }

            model.houseBillsSorted = household.Bills.OrderBy(b => b.DateDue).ToList();

            return View(model);
        }

        [Authorize]
        public async Task<ActionResult> JoinHouse(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var household = dbContext.HouseHolds.FirstOrDefault(x => x.Id == id);

            if (household == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            var userId = User.Identity.GetUserId();
            var user = dbContext.Users.FirstOrDefault(x => x.Id == userId);
            user.UserInfo.RequestToJoin(household, user.UserInfo);
            dbContext.SaveChanges();

            return RedirectToAction("Details", new { id = household.Id });
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(HouseHold model)
        {

            if (ModelState.IsValid)
            {
                dbContext.HouseHolds.Add(model);

                var userId = User.Identity.GetUserId();
                var appUser = dbContext.Users.FirstOrDefault(x => x.Id == userId);
                model.Users.Add(appUser.UserInfo);
                dbContext.SaveChanges();
                //model.AddRoommate(appUser.UserInfo);
                model.HeadOfHouseHold = appUser.UserInfo;

                dbContext.SaveChanges();
                return RedirectToAction("Details", new {id = model.Id});
            }

            return View(model);
        }

        [Authorize]
        // Return not working
        public async Task<ActionResult> AcceptRoommate(int? id, int requestId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var household = dbContext.HouseHolds.FirstOrDefault(x => x.Id == id);

            var userId = User.Identity.GetUserId();
            var currentUser = await UserManager.FindByIdAsync(userId);
            //var appUser = UserManager.Users.FirstOrDefault(x => x.UserInfo.Id == requestId);

            var request = dbContext.JoinRequests.FirstOrDefault(x => x.Id == requestId);

            if (household == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }
            if (request == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            currentUser.UserInfo.AcceptRequest(request.User, request.HouseHold);


            dbContext.SaveChanges();
            return RedirectToAction("Details", new { id = household.Id });

        }

        [Authorize]
        // Return not working
        public async Task<ActionResult> RejectRoommate(int? id, int requestId)
        {
            var household = dbContext.HouseHolds.FirstOrDefault(x => x.Id == id);

            //var userId = User.Identity.GetUserId();
            //var currentUser = await UserManager.FindByIdAsync(userId);

            var request = dbContext.JoinRequests.FirstOrDefault(x => x.Id == requestId);

            if (household == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }
            if (request == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            household.RemoveRequest(request);

            dbContext.SaveChanges();
            return RedirectToAction("Details", new { id = household.Id });
        }

    }
}

BillPayingWebsite/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>

<p>Members</p>
<p>Matthew Williams</p>
<p>Judah Perez - Programmer</p>

<p>Robert Fleury</p>

<p>Preston Richey - Richie Rich</p>
<p>Joshua Cantero</p>
<p>Vihn Vu</p>

BillPayingWebsite/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BillPayingWebsite/Views/Home/Index.cshtml
    @{
    ViewBag.Title = "Home Page";
    }



    <div class="row">
        <div class="jumbotron">
            <div class="container">
                <h1> Welcome to Billsplit</h1>
                <a href="@Url.Action("Login", "Account")" class="btn btn-primary" role="Log In" style="float: left;"><span>Log In</span></a>
                <div class="col-sm-6 col-md-4">
                    <a href="@Url.Action("Register", "Account")" class="btn btn-primary" role="Register" style="float: left;"><span>Register</span></a>
                </div>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <a href="@Url.Action("Index", "House")" class="btn btn-primary" role="Houses"> House Search</a>
                <img src="https://upload.wikimedia.org/wikipedia/commons/f/f8/Ellen_H._Swallow_Richards_House_Boston_MA_01.jpg" alt="House" class="img-circle" height="144" width="177">
            </div>
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <a href="@Url.Action("Index", "Roommates")" class="btn btn-primary" role="other"> Roomate Search</a>
                <img src="https://upload.wikimedia.org/wikipedia/commons/d/df/John_Crowe_Ransom_1941.jpg" alt="roomate" class="img-circle" height="144" width="177">
            </div>
        </div>
    </div>